# Generated by Django 4.2.30 on 2026-06-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_competition_deadline_competition_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
