# Generated by Django 4.2.30 on 2026-06-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_competition_drive_file_id_news_drive_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='drive_file_id',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='news',
            name='drive_file_id',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_url',
        ),
        migrations.AddField(
            model_name='competition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='competition/images/'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/images/'),
        ),
    ]
