# Generated by Django 4.2.30 on 2026-06-26 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0004_replace_drive_with_local_imagefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_point_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'กิจกรรมสะสมแต้ม',
                'verbose_name_plural': 'กิจกรรมสะสมแต้ม',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPointProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'โปรไฟล์คะแนน',
                'verbose_name_plural': 'โปรไฟล์คะแนน',
            },
        ),
        migrations.CreateModel(
            name='PointSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_image', models.ImageField(upload_to='point_proofs/', verbose_name='ภาพหลักฐาน')),
                ('status', models.CharField(choices=[('pending', 'รอตรวจสอบ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ไม่อนุมัติ')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('admin_note', models.TextField(blank=True, default='', verbose_name='หมายเหตุ')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='portal.pointactivity', verbose_name='กิจกรรม')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_point_submissions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'คำขอสะสมแต้ม',
                'verbose_name_plural': 'คำขอสะสมแต้ม',
                'ordering': ['-created_at'],
            },
        ),
    ]
